### ISSUE TITLE
args --> kw issues

### ISSUE THREAD

**Issue by quecloud** [willsheffler/rpxdock#6]
Hey will, are you trying to replace all *args with **kw and args.option with kw.option?

It looks like that may have introduced a few typos and inconsistencies that break things. I'm happy to help clean them up, just wanted to make sure I was on the same page with what you are trying to accomplish.

Q

**Comment by willsheffler** [comment]
Shoot, there must be stuff my tests aren't covering... sorry of its a hassle. Maybe open a pull request with your fixes? Or point me to the issues?

**Comment by quecloud** [comment]
kk, the one that should probably be addressed asap a type on app/dock.py
line 103:

bodies = [[rp.Body(fn, allowed_res=ar2**kw)


should read


bodies = [[rp.Body(fn, allowed_res=ar2, **kw)
