### ISSUE TITLE
what is pickle file and how to read it ?

### ISSUE THREAD

**Issue by 1497415080** [willsheffler/rpxdock#65]
Hi, I am trying to design a protein nanoparticle by rpxdock, and I use the dock.py to dock a trimer with a pentamer in I53 structure, but the output file is a pickle file which I don't know how to handle with.

**Comment by yhsia** [comment]
Hello,

The RPXDock manuscript is now on bioRxiv.
Please give this a read through and let us know if there are any further questions.
https://www.biorxiv.org/content/10.1101/2022.10.25.513641v1?rss=1
